name: Build PyPI package

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  build-publish-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==${{ vars.POETRY_VERSION }} --python $(which python)
        shell: bash

      - name: Poetry path
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        shell: bash

      - name: Set version and build LCA-Modeller
        run: |
          poetry version $( echo ${{ github.ref }} | sed 's%refs/tags/%%' )
          poetry build
        shell: bash

      - name: publish to PyPI
        env:
          TOKEN: ${{ secrets.PyPI }} # do not use the secret directly in run command, it would write it plainly in the log
        run: |
          poetry config pypi-token.pypi "$TOKEN"
          poetry publish